name: Antarctica Memorabilia
favicon: null
layout_spectrum: 0.99935
typography_spectrum: 0.75485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c3d0dd'
    - '#a4a4a6'
    - '#454e61'
    - '#2a2925'
  brandStrength: 0.5
  lightness: 0.8711834521964192
  saturation: 0.9834890423808247
  rhythmicContrast: 0.27665764978155494
purpose: []
